### GET Config
GET {{host}}/config

### POST Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "gerson.msj@gmail.com",
    "senha": "gerson"
}

### DELETE Login
DELETE {{host}}/login

### POST Cadastro
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "Gerson",
    "familia": "Moraes",
    "email": "gerson.msj@gmail.com",
    "senha": "gerson"
}


### GET Familia

GET {{host}}/familia

### POST Familia
POST {{host}}/familia
Content-Type: application/json

[
    {
        "id": 0,
        "nome": "Silva",
        "remove": true
    },
    {
        "id": 0,
        "nome": "Moraes",
        "remove": true
    }
]
