### GET Config
GET {{host}}/config

### POST Config
POST {{host}}/config
Content-Type: application/json

{
    "nome": "Moraes",
    "integrantes": [
        {
            "id": 4,
            "nome": "Gerson",
            "email": "gerson.msj@gmail.com",
            "senha": "gerson",
            "principal": true,
            "categorias": [
                {
                    "id": 1,
                    "nome": "Salário",
                    "categoriaTipo": "RECEITA"
                },
                {
                    "id": 5,
                    "nome": "Extra",
                    "categoriaTipo": "RECEITA",
                    "remove": true
                }
            ]
        },
        {
            "id": 5,
            "nome": "Paula",
            "email": "paula@gmail.com",
            "senha": "paula",
            "principal": false,
            "categorias": [
                {
                    "id": 3,
                    "nome": "Salário",
                    "categoriaTipo": "RECEITA"
                }
            ]
        }
    ]
}


### POST Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "gerson.msj@gmail.com",
    "senha": "gerson"
}

### DELETE Login
DELETE {{host}}/login

### POST Cadastro
POST {{host}}/cadastro
Content-Type: application/json

{
    "nome": "Gerson",
    "familia": "Moraes",
    "email": "gerson.msj@gmail.com",
    "senha": "gerson"
}


### GET Familia

GET {{host}}/familia

### POST Familia
POST {{host}}/familia
Content-Type: application/json

[
    {
        "id": 0,
        "nome": "Silva",
        "remove": true
    },
    {
        "id": 0,
        "nome": "Moraes",
        "remove": true
    }
]
